version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - user-service
      - event-service
      - certificate-service

  user-service:
    build:
      context: ./user-service
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  event-service:
    build:
      context: ./event-service
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  certificate-service:
    build:
      context: ./certificate-service
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge